//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int SECUENCIAL { get; set; }
        public int SECUENCIALPRESTAMO { get; set; }
        public decimal VALORPAGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal SALDOPRESTAMO { get; set; }
    
        public virtual PRESTAMO PRESTAMO { get; set; }
    }
}
