//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Proxies.Persona {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PersonaWSSoap", Namespace="http://tempuri.org/")]
    public partial class PersonaWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GuardarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarPorIdentificacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PersonaWS() {
            this.Url = global::Proxies.Properties.Settings.Default.Proxies_Persona_PersonaWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GuardarCompletedEventHandler GuardarCompleted;
        
        /// <remarks/>
        public event ListarCompletedEventHandler ListarCompleted;
        
        /// <remarks/>
        public event BuscarPorIdentificacionCompletedEventHandler BuscarPorIdentificacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guardar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonaMSJ Guardar(PersonaMSJ personamsj) {
            object[] results = this.Invoke("Guardar", new object[] {
                        personamsj});
            return ((PersonaMSJ)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarAsync(PersonaMSJ personamsj) {
            this.GuardarAsync(personamsj, null);
        }
        
        /// <remarks/>
        public void GuardarAsync(PersonaMSJ personamsj, object userState) {
            if ((this.GuardarOperationCompleted == null)) {
                this.GuardarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarOperationCompleted);
            }
            this.InvokeAsync("Guardar", new object[] {
                        personamsj}, this.GuardarOperationCompleted, userState);
        }
        
        private void OnGuardarOperationCompleted(object arg) {
            if ((this.GuardarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarCompleted(this, new GuardarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonaMSJ[] Listar() {
            object[] results = this.Invoke("Listar", new object[0]);
            return ((PersonaMSJ[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAsync() {
            this.ListarAsync(null);
        }
        
        /// <remarks/>
        public void ListarAsync(object userState) {
            if ((this.ListarOperationCompleted == null)) {
                this.ListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarOperationCompleted);
            }
            this.InvokeAsync("Listar", new object[0], this.ListarOperationCompleted, userState);
        }
        
        private void OnListarOperationCompleted(object arg) {
            if ((this.ListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCompleted(this, new ListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarPorIdentificacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PersonaMSJ BuscarPorIdentificacion(string identificacion) {
            object[] results = this.Invoke("BuscarPorIdentificacion", new object[] {
                        identificacion});
            return ((PersonaMSJ)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarPorIdentificacionAsync(string identificacion) {
            this.BuscarPorIdentificacionAsync(identificacion, null);
        }
        
        /// <remarks/>
        public void BuscarPorIdentificacionAsync(string identificacion, object userState) {
            if ((this.BuscarPorIdentificacionOperationCompleted == null)) {
                this.BuscarPorIdentificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarPorIdentificacionOperationCompleted);
            }
            this.InvokeAsync("BuscarPorIdentificacion", new object[] {
                        identificacion}, this.BuscarPorIdentificacionOperationCompleted, userState);
        }
        
        private void OnBuscarPorIdentificacionOperationCompleted(object arg) {
            if ((this.BuscarPorIdentificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarPorIdentificacionCompleted(this, new BuscarPorIdentificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonaMSJ {
        
        private int sECUENCIALField;
        
        private string cODIGOTIPOIDENTIFICACIONField;
        
        private string iDENTIFICACIONField;
        
        private string pRIMERNOMBREField;
        
        private string sEGUNDONOMBREField;
        
        private string pRIMERAPELLIDOField;
        
        private string sEGUNDOAPELLIDOField;
        
        private bool eSTAACTIVOField;
        
        /// <remarks/>
        public int SECUENCIAL {
            get {
                return this.sECUENCIALField;
            }
            set {
                this.sECUENCIALField = value;
            }
        }
        
        /// <remarks/>
        public string CODIGOTIPOIDENTIFICACION {
            get {
                return this.cODIGOTIPOIDENTIFICACIONField;
            }
            set {
                this.cODIGOTIPOIDENTIFICACIONField = value;
            }
        }
        
        /// <remarks/>
        public string IDENTIFICACION {
            get {
                return this.iDENTIFICACIONField;
            }
            set {
                this.iDENTIFICACIONField = value;
            }
        }
        
        /// <remarks/>
        public string PRIMERNOMBRE {
            get {
                return this.pRIMERNOMBREField;
            }
            set {
                this.pRIMERNOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string SEGUNDONOMBRE {
            get {
                return this.sEGUNDONOMBREField;
            }
            set {
                this.sEGUNDONOMBREField = value;
            }
        }
        
        /// <remarks/>
        public string PRIMERAPELLIDO {
            get {
                return this.pRIMERAPELLIDOField;
            }
            set {
                this.pRIMERAPELLIDOField = value;
            }
        }
        
        /// <remarks/>
        public string SEGUNDOAPELLIDO {
            get {
                return this.sEGUNDOAPELLIDOField;
            }
            set {
                this.sEGUNDOAPELLIDOField = value;
            }
        }
        
        /// <remarks/>
        public bool ESTAACTIVO {
            get {
                return this.eSTAACTIVOField;
            }
            set {
                this.eSTAACTIVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GuardarCompletedEventHandler(object sender, GuardarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonaMSJ Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonaMSJ)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListarCompletedEventHandler(object sender, ListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonaMSJ[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonaMSJ[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarPorIdentificacionCompletedEventHandler(object sender, BuscarPorIdentificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarPorIdentificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarPorIdentificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonaMSJ Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonaMSJ)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591